### ISSUE TITLE
Migrate to API v1 stable

### ISSUE THREAD

**Issue by ajimix** [parker-codes/coda-js#12]
Coda just released v1 stable of their API. The project should be migrated to continue working with Coda

[Official announcement](https://coda.io/api-migration-guide)

**Comment by parker-codes** [comment]
Thanks @ajimix for letting us know about the announcement!

I don't have the availability to make these updates at the moment. We have until **August 21st** though I don't like doing things last minute. Does anyone want to tackle this? Even taking one or two of the updates would be very helpful!

- [x] **1.** update request path to use `v1` in API.ts
- [x] **2.** we didn't have a views API before so users can just use the table API 😂
    - [x] note the new `tableType` property in models/Table.ts comment
    - [x] add something to README examples that shows `tableType` can be access to tell if it's a table or view
- [x] **3.** remove all references to Folders API
- [x] **4.** convert all references of Sections to Pages (eg. `getPage(...)` instead of `getSection(...)`)
- [x] **5.** add a short disclaimer in the README about pagination updates in Coda's v1 API and point to [Migration Guide](https://coda.io/api-migration-guide) Pagination section
- [x] **6.** add support for new `mutationStatus` API endpoint; Currently these mutative calls are returning `Promise<boolean>` based on if the status code matches `200`. Since we are already doing request error handling, returning a boolean is not really helpful.
    - [x] a base level `mutationStatus(requestId: string)` method in case people want to do it manually
    - [x] mutating methods like `row.update(...)` should return an instance of a new PendingRequest class, which has a method for `completed()`, which returns `Promise<boolean>` of whether it has been completed or not (handles the call to mutation status within, perhaps using the base level `mutationStatus` method)
    - [x] add these as examples in README, like:
        - `const complete = await coda.mutationStatus('290fe9029-f92090e-akbiu1i3r')`
        - `const request = await row.delete();   const complete = await request.complete();`
    - I could see added methods in the future like `row.deleteSync()` that run a short interval until the response comes back true, but that's beyond the scope of this update!


If you have any questions before tackling this or you want to claim some of the items, just let me know.

CC @mjoyce @svennu @inguelberth @fenixsolorzano

**Comment by parker-codes** [comment]
I've created a `v1-migration` branch for contributing to.

**Comment by thecodelearner** [comment]
@parker-codes I've been using coda-js for about two months now in a professional use case application. I started with coda-js because honestly it was a hell lot simple to use and not at all complicated. As such,  I'd like to help in bumping up to v1stable.
I haven't done much open source contributions but I'd be more than happy to help tackle the small changes while migration to v1stable.
Could you guide me on what would be some high priority changes so I can go ahead fork it and work on them? 

Meanwhile I will go through the migration guide and their stable api docs. Thanks a ton for making this wrapper api.

**Comment by parker-codes** [comment]
@thecodelearner Thanks for wanting to help out! I'm glad this package has helped!

Since you say you're newer to open source, I suggest starting with doing a more simple task and then taking on the more challenging ones if you're up for it. This migration to v1 shouldn't be too difficult even if one were to do the whole thing alone. Just don't feel like you have to. 😊

Here's what contributing might look like:
1. Fork the repo.
2. Checkout the `v1-migration` branch (which is currently identical to the `master` branch).
3. Look through the project structure. You don't have to memorize everything - just focus on getting an idea of where certain files go and how they work. 
4. Do the first task higher up in this issue:
> update request path to use v1 in API.ts
5. Commit that change with a simple commit message.
6. Do any other tasks and commit them to your fork also. Ask as many questions as you want if something isn't clear.
7. When you're ready, create a PR (GitHub has some helpful buttons to do this in it's interface, but if you'd like some help with it, let me know). You can then comment in this thread and paste the link to the PR for review.
8. We'll give you feedback. You don't have to worry about negative comments - there are always rude people, but if you ever encounter them just don't pay attention to them. If there are any suggestions on changes, we'll point it out.
9. The PR gets merged into the `coda-js` repo's `v1-migration` branch. If there are many commits, I can "squash" them all into one big commit. Once all of the migration tasks are complete, I'll merge it into master and bump the package version to the next major release.

**Comment by thecodelearner** [comment]
@parker-codes will do. Thanks a lot.

**Comment by parker-codes** [comment]
@thecodelearner Just got a PR (#15) from someone that takes care of task 1 through 4. Sometimes things move fast. If you're not up for the other tasks in the list, I understand, but I'd still love your help!

**Comment by thecodelearner** [comment]
Ah no worries. I'll try to look for items 5+ in the list

**Comment by parker-codes** [comment]
I'm working on number 6 (pending statuses).

Finished that task: 6d50a02

**Comment by parker-codes** [comment]
Finished task number 5: a14f009

I will publish this as `v4` of `coda-js`!
